"""Regenerate the single-file, vendorable micromcp.py from the package.

    python tools/bundle.py                  # writes build/micromcp.py
    python tools/bundle.py --check          # exits 1 if build/micromcp.py is stale

The modules are concatenated in dependency order with their intra-package
imports removed (found with `ast`, so indented and multi-line forms are
handled); everything else is verbatim, so the bundle behaves exactly like the
package. CI regenerates it and runs every suite against it.
"""
import argparse
import ast
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PKG = ROOT / "src" / "micromcp"
ORDER = ["_constants", "errors", "markers", "docstrings", "schema", "registry",
         "core", "wsgi", "asgi", "contrib/django"]


def _strip(src: str, *, docstring: bool, relative_imports: bool, all_: bool) -> str:
    """Remove the parts of a module that only make sense inside the package."""
    tree = ast.parse(src)
    lines = src.splitlines(keepends=True)
    drop: set[int] = set()

    def span(node):
        for ln in range(node.lineno, node.end_lineno + 1):
            drop.add(ln)

    if docstring and tree.body and isinstance(tree.body[0], ast.Expr) \
            and isinstance(tree.body[0].value, ast.Constant) \
            and isinstance(tree.body[0].value.value, str):
        span(tree.body[0])
    for node in ast.walk(tree):
        if relative_imports and isinstance(node, ast.ImportFrom) and node.level > 0:
            span(node)
        if isinstance(node, ast.ImportFrom) and node.module == "__future__":
            span(node)
        if all_ and isinstance(node, ast.Assign) and any(
                isinstance(t, ast.Name) and t.id == "__all__" for t in node.targets):
            span(node)
    return "".join(line for i, line in enumerate(lines, 1) if i not in drop)


def build() -> str:
    init_src = (PKG / "__init__.py").read_text()
    init = ast.parse(init_src)
    header = ast.get_docstring(init, clean=False)
    version = re.search(r'^__version__ = "([^"]+)"', init_src, re.M).group(1)
    all_node = next(n for n in init.body if isinstance(n, ast.Assign)
                    and isinstance(n.targets[0], ast.Name) and n.targets[0].id == "__all__")
    all_src = ast.get_source_segment(init_src, all_node)
    out = [f'"""{header}"""\n',
           "# Generated by tools/bundle.py from the micromcp package; do not edit.\n",
           "from __future__ import annotations\n\n",
           f'__version__ = "{version}"\n\n',
           all_src + "\n"]
    for name in ORDER:
        src = (PKG / f"{name}.py").read_text()
        src = _strip(src, docstring=True, relative_imports=True, all_=True)
        out.append(f"\n# {'=' * 76}\n# {name}.py\n# {'=' * 76}\n")
        out.append(src.strip("\n") + "\n")
    text = "".join(out)
    # A relative import that survived would only fail at call time; refuse now.
    for node in ast.walk(ast.parse(text)):
        if isinstance(node, ast.ImportFrom) and node.level > 0:
            raise SystemExit(f"bundle: relative import left at line {node.lineno}")
    return text


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--out", default=str(ROOT / "build" / "micromcp.py"))
    args = ap.parse_args()
    text = build()
    target = pathlib.Path(args.out)
    if args.check:
        if not target.exists() or target.read_text() != text:
            print(f"{target} is stale; run python tools/bundle.py", file=sys.stderr)
            return 1
        print(f"{target} is up to date")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text)
    print(f"wrote {target} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
